### ISSUE TITLE
! cause exception

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm-nxos#100]
### Description of Issue/Question
usually when we are loading configuration to ios, we use ! between commands. However it seems nxos will throw error when load ! between commands

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[ *] Yes
[ ] No

### Setup
send ! during load_merge config

### napalm-nxos version
(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

```
latest version
```

### NX-OS version
(Paste verbatim output from `show version | json` between quotes below)

```
any nxos
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
N/A
```

**Comment by mirceaulinic** [comment]
Hi @sincerywaing - we are currently in the process of reunification, please check https://napalm-automation.net/reunification/.
Going forward, we'd like to ask you to submit Pull Requests and Issue to the main repository: https://github.com/napalm-automation/napalm.
If this issue persists, don't hesitate to report at https://github.com/napalm-automation/napalm.

Thanks for understanding!
