### ISSUE TITLE
nxos replace operation - add to docs

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#105]
Can't use `show run` for initial config of replace operation; need to use a checkpoint file.

```
checkpoint test-checkpoint-kb description some text 
# need all to get defaults
show checkpoint test-checkpoint-kb all
```

need to be careful about copy-and-paste from box as line-wrap can introduce invalid newlines for very long lines.

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/446
