### ISSUE TITLE
device.get_interfaces_ip() fails if no ipv6 interfaces

### ISSUE THREAD

**Issue by jzohrab** [napalm-automation/napalm-nxos#11]
I have a lab device that has ipv4 interfaces set up, but not ipv6.  get_interfaces_ip() fails with message `AttributeError: 'str' object has no attribute 'get'`.

```
nx-osv-1# show ip int brief
IP Interface Status for VRF "default"(1)
Interface            IP Address      Interface Status
Eth2/1               10.1.2.0        protocol-up/link-up/admin-up     

nx-osv-1# show ipv6 int brief
IPv6 Interface Status for VRF "default"(1)
Interface        IPv6 Address/Link-local Address           Interface Status 
                                                           prot/link/admin
```

The code calls `_get_command_table` first for ipv4 then for v6.  When it calls for v6, the returned data is as follows:

```
{'ins_api': {'outputs': {'output': {'body': '', 'input': 'show ipv6 interface', 'code': '200', 'msg': 'Success'}}, 'version': '1.2', 'type': 'cli_show', 'sid': 'eoc'}}
```

so 'body' is returned but is a string.  `_get_reply_table` fails at that point.

**Comment by jzohrab** [comment]
Changing `_get_reply_body` to the below works (tested locally), I'll submit an initial patch now:

```
    def _get_reply_body(self, result):
        # useful for debugging
        ret = result.get('ins_api', {}).get('outputs', {}).get('output', {}).get('body', {})
        if not isinstance(ret, dict):
            return {}
        return ret
```

**Comment by jzohrab** [comment]
Addressed in https://github.com/napalm-automation/napalm-nxos/pull/12

**Comment by mirceaulinic** [comment]
Following my comment in #12: let's try to find solutions related strictly to the method in cause (here `get_interfaces_ip`) and provide something similar to what David proposed in https://github.com/napalm-automation/napalm-eos/pull/18

**Comment by jzohrab** [comment]
Got it, will look tomorrow.  Thanks for the note.

**Comment by jzohrab** [comment]
PR #12 is merged, closing.
