### ISSUE TITLE
Issue connecting to NX-OS via HTTPS

### ISSUE THREAD

**Issue by jventri** [napalm-automation/napalm-nxos#114]
### Description of Issue/Question

Unable to connect to nxapi on port 443 (Nexus). Due to a Cisco bug I had to change the port to an alternate and it works

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[ ] Yes
[ x] No

### Setup
Error I was getting

```{"changed": false, "failed": true, "msg": "cannot connect to device: HTTPSConnectionPool(host='Nexus-2', port=443): Max retries exceeded with url: /ins (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1faf0e8fd0>, 'Connection to Nexus-2 timed out. (connect timeout=1)'))"}```

### napalm-nxos version
(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

```
jventri@lt1:~/Plays> sudo pip freeze | grep napalm
napalm==1.2.0
napalm-base==0.24.3
napalm-eos==0.5.2
napalm-fortios==0.3.1
napalm-ibm==0.1.6
napalm-ios==0.5.1
napalm-iosxr==0.4.6
napalm-junos==0.6.2
napalm-nxos==0.6.0
napalm-panos==0.3.0
napalm-pluribus==0.5.0
napalm-ros==0.2.0
napalm-vyos==0.1.2
napalm-yang==0.0.7

```

### NX-OS version
(Paste verbatim output from `show version | json` between quotes below)

```
Software
  BIOS:      version 3.3.0
  Power Sequencer Firmware:
             Module 0: v5.0
             Module 1: v2.0
             Module 8: v2.0
  Fabric Power Sequencer Firmware: Module 0: version v3.0
  Microcontroller Firmware:        version v1.1.0.4
  QSFP Microcontroller Firmware:
             Module 1: v1.3.0.0
             Module 8: v1.3.0.0
  SFP Microcontroller Firmware:
             Module not detected
  CXP Microcontroller Firmware:
             Module not detected
  kickstart: version 7.3(2)N1(1)
  system:    version 7.3(2)N1(1)

```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
https://bst.cloudapps.cisco.com/bugsearch/bug/CSCuw39988/?referring_site=bugquickviewredir
Had to change the port to an alternate port for it to work

```

**Comment by mirceaulinic** [comment]
Hi @jventri - we are currently in the process of reunification, please check https://napalm-automation.net/reunification/.
Going forward, we'd like to ask you to submit Pull Requests and Issue to the main repository: https://github.com/napalm-automation/napalm.
If this issue persists, don't hesitate to report at https://github.com/napalm-automation/napalm.

Thanks for understanding!
