### ISSUE TITLE
get_bgp_neighbors has a hard-coded uptime (-1) and has hard-coded the prefixes (-1)

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#116]
Need to work which command in NX-API we can retrieve this data from. It doesn't look to be present in:

```
show bgp sessions vrf all | json
```

Although uptime can maybe be worked out from that command.

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/443
