### ISSUE TITLE
Parsing issue on get_mac_address_table for nxos_ssh

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#140]
From show mac address-table. Parser will choke on the extra space in the interface name

```
 500      0023.e940.4f83    dynamic     ~~~      F    F  vPC Peer-Link
  500      0025.b5b0.304e    dynamic     ~~~      F    F  vPC Peer-Link
```

**Comment by ktbyers** [comment]
Fix for this is to just preprocess 'vPC Peer-Link' this string and eliminate the space:

```
vPC-Peer-Link
```

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/441
