### ISSUE TITLE
get_interfaces_ip() fails with error "'list' object has no attribute 'get'"

### ISSUE THREAD

**Issue by jzohrab** [napalm-automation/napalm-nxos#17]
On my current device, the raw returned data from nxapi is as follows (abridged):

```
{'ins_api':
  {'outputs':
    {'output':
      {'body':
         {'TABLE_intf': [
             {'ROW_intf': {'admin-state': 'up', ..., 'intf-name': 'Vlan123', ... }},
             {'ROW_intf': {'admin-state': 'up', ..., 'intf-name': 'Ethernet2/1', ... }}
           ],
           'TABLE_vrf': [
             {'ROW_vrf': {'vrf-name-out': 'default'}},
             {'ROW_vrf': {'vrf-name-out': 'default'}}
           ]
         },
       'code': '200',
       'input': 'show ip interface',
       'msg': 'Success'
      }
    },
   'sid': 'eoc',
   'type': 'cli_show',
   'version': '1.2'
  }
}
```

`_get_reply_table` is as follows:

```
def _get_reply_table(self, result, tablename, rowname):
    # still useful for debugging
    return self._get_reply_body(result).get(tablename, {}).get(rowname, [])
```

tablename = "TABLE_intf", so `self._get_reply_body(result).get(tablename, {})` will return the following:

```
[
  {'ROW_intf': {'admin-state': 'up', ..., 'intf-name': 'Vlan123', ... }},
  {'ROW_intf': {'admin-state': 'up', ..., 'intf-name': 'Ethernet2/1', ... }}
]
```

This isn't a hash, so subsequent `.get(rowname, [])` fails, where rowname = "ROW_intf".

Is there something about this returned data that is incorrect, i.e. is this device somehow "broken"?

**Comment by jzohrab** [comment]
Based on the code, I would have expected the returned data to look something like this:

```
'TABLE_intf': {'ROW_intf': [
             {'admin-state': 'up', ..., 'intf-name': 'Vlan123', ... },
             {'admin-state': 'up', ..., 'intf-name': 'Ethernet2/1', ... }
           ]},
```

But I really don't know.

**Comment by mirceaulinic** [comment]
Thanks @jzohrab for reporting this, I see the same JSON output as yours. Will have a look tomorrow!

**Comment by mirceaulinic** [comment]
And the same for IPv6 addr

**Comment by jzohrab** [comment]
np, I'd submit a fix but I don't think it will be accepted any time soon.  To submit it, I'd need to pull over some code from #16, or similar, which is currently waiting for merge.  Alas.  Thanks @mirceaulinic

**Comment by mirceaulinic** [comment]
You can come with a PR if you want to.
Can you be more specific, what do you need from #16? To fix this you only need to apply changes in `nxos.py`. I assume you don't want to reuse stuff from `get_bgp_neighbors`, do you? :P

**Comment by jzohrab** [comment]
Re stuff from #16, I'd like to pull over the change to the Fake device that lets me set the returned data, `set_mock_file_overrides`, so we can try out different scenarios.  I was burned with this API before, when the ipv6 wasn't set, and this is another issue.  It would be nice to put some good scenarios together so that we can be more confident in code.

**Comment by mirceaulinic** [comment]
I see your point, I appreciate your commitment. But fixing the bugs comes first and the good scenarios I would cathegorise as the nice-to-have features.
So I would suggest to open for the moment a PR strictly to fix this bug. Afterwards, you can either rebase it when #16 is merged, either open a different PR. Does this make sense to you?

**Comment by mirceaulinic** [comment]
Also, keep in mind that "good scenarios" imply lengthy discussions. Or, each issue ideally should have a PR that fixes the bug and all discussions should be limited to that issue only. Otherwise, we may end up with a massive mess.

**Comment by jzohrab** [comment]
I would prefer adding test coverage at the time of making the change, to ensure I don't break anything anew, rather than adding it afterwards.  I usually have my devs write a failing test case to demonstrate something is broken, fix the code, and then ensure the tests pass, as part of their workflow.  That's my recommendation -- you're the owner, so it's your call.  :-)

For good scenarios, I'd assume the following would be sufficient:
- only ipv4 config'd
- single ROW_intf  (returns dict)
- multiple ROW_intf records  (returns list)
- single TABLE_int  (same as above)

**Comment by mirceaulinic** [comment]
I'm not the owner, @dbarrosop is. I'm just making suggestions :)
At the end of the day, I would recommend you to do what you feel more comfortable. But I really want to keep things straight.
Moreover, David proposed a different testing framework and I don't think is the right timing and the right place to make concomitantly changes.
From my side, please open for the moment a PR that fixes the bug (changes applies strictly in nxos.py). Then we'll see.

**Comment by jzohrab** [comment]
Got it.  I know DB's got some new testing ideas coming and it's a juggling act to keep things straight sometimes.

What I'll do is make some tests to check my implementation and I'll run them, but I won't commit those tests in the PR.  I'll do something so that these tests can be incorporated later.  I've read through the code David is proposing, I think I know what's coming up.

**Comment by jzohrab** [comment]
Submitted a PR, with notes in there.

I _did_ end up building on the existing PR.  My internal project needs these fixes in, and part of the changes from the earlier PR ensure that the changes actually work.  I will fix these tests in the future when the new testing framework is ready, but I don't have a timeframe for when that will be done, and the code currently doesn't handle a realistic situation.

**Comment by dbarrosop** [comment]
Main challenge with testing napalm is that we have real devices versus mocked devices and then we have to ensure that all the network drivers behave as similar as possible... But I agree we have to improve that part as much as possible. We have to build on the PR I sent the other day, work on the test cases, etc. so I hope you both can give as much feedback as possible to rewrite those : )

Back to this issue, can we close it? Is there anything pending here?

P.S: Regarding the ownership question, I was thinking in opening that somehow. Still thinking on how to do it but I will probably give "ownership" to the main contributors for each driver and keep a "tight" control of just `napalm` and `napalm-base` to ensure that someone coordinates those. For drivers like `napalm-nxos` I am mostly a bottleneck... Anyway, I will probably open an issue or something before the end of summer to discuss some ideas on how to best do this but I wanted to mention it because there was some "ownership" comments on this thread ;)

**Comment by mirceaulinic** [comment]
Hi David, please don't close this issue yet. @jzohrab opened #18 to fix it but it looked too messy to me and he decided to close it for the time moment. As #16 has been merged and he has already the code prepared to kill this bug, probably we'll have another PR very soon.

**Comment by jzohrab** [comment]
@dbarrosop - re real devices vs mocked devices, yes that's a tough one.  My thought for that is that any failing scenario for a device would be a new test case using data from that real device, maybe indicating the device os version in the mock file name/path.  I think the new testing framework will help with that a lot.  The data that I gave was from a real Nexus device in a VIRL lab.

I'm going to get that code ready, will be nice to PR it and get it done.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/pull/41
