### ISSUE TITLE
nxos driver should default to https not http

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#36]
```
        self.protocol = optional_args.get('nxos_protocol', 'http')
```

**Comment by mirceaulinic** [comment]
That would make sense @ktbyers. Although will break the functionality for some users, I think is the right thing to do.

**Comment by ktbyers** [comment]
Yes, maybe we can make it graceful (i.e. not break for a transition period).

try https first. If that fails try 'http' and print a warning.

At a later date remove the fallback to http and the warning message.

**Comment by mirceaulinic** [comment]
Can we close this one now @ktbyers?

**Comment by ktbyers** [comment]
No it is still open...nxos still defaults to HTTP.

The fix I put in allowed HTTPS to work with non-standard port and unsigned certificate, but it is still defaulting to clear-text.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/commit/0bd7f01cec53a3f5b9f1c96e04eef9191fb6132c

**Comment by ktbyers** [comment]
Nope, still defaults to HTTP and not HTTPS:

https://github.com/napalm-automation/napalm-nxos/blob/develop/napalm_nxos/nxos.py#L64

**Comment by mirceaulinic** [comment]
Thanks @ktbyers for reopening - it looks like merging the PR closed the issue automatically and we missed that.
