### ISSUE TITLE
nxos driver does not save change to startup-config on commit

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-nxos#39]
Performed merge operation changing the hostname, did commit() action. Verified running config was changed via SSH.

Checked startup config and saw it wasn't changed.

Using latest develop branch of napalm-nxos as of 2016-10-10

**Comment by mirceaulinic** [comment]
> Checked startup config and saw it wasn't changed.

What a surprise :)

That's a very serious one!
