### ISSUE TITLE
Atomic Merge

### ISSUE THREAD

**Issue by jasmas** [napalm-automation/napalm-nxos#77]
Could the merge process be made atomic by taking a snapshot that could be rolled back just before the merge? I thought about writing an enhancement, but I wanted to check here first to see if there is some other technical reason that merges cannot be atomic on this platform.

**Comment by ktbyers** [comment]
@jedelman8 @itdependsnetworks

**Comment by jedelman8** [comment]
Makes sense.  This is actually how we do atomic changes with Ansible on
nxos using the nxos_rollback and ntc_rollback modules.  So yes, in
agreement for merges:  Step 1.  Create a checkpoint file.  Step 2: send
commands.  Step 3: rollback on error

**Comment by mirceaulinic** [comment]
Moved to https://github.com/napalm-automation/napalm/issues/447
