### ISSUE TITLE
nve interface breaks get_interfaces()

### ISSUE THREAD

**Issue by tomatopeel** [napalm-automation/napalm-nxos#8]
```
interface nve1
  no shutdown
  source-interface loopback5
  overlay-encapsulation vxlan
  host-reachability protocol bgp
```

This interface configuration causes the following issue:

```
(Pdb) pp intf_info
{'interface': 'nve1', 'type': 'unknown'}
(Pdb) n
> /home/user/Envs/Envs/napalm-venv/lib/python2.7/site-packages/napalm_nxos/nxos.py(206)get_interfaces()
    -> formatted_info['is_up'] = 'up' in intf_info.get('state', intf_info.get('admin_state', '')).lower()
    (Pdb) 
    > /home/user/Envs/Envs/napalm-venv/lib/python2.7/site-packages/napalm_nxos/nxos.py(207)get_interfaces()
    -> formatted_info['is_enabled'] = 'up' in intf_info.get('admin_state').lower()
    (Pdb) 
    AttributeError: "'NoneType' object has no attribute 'lower'"
```

**Comment by mirceaulinic** [comment]
Hi @thomasodot looks more rather like an issue with the underneath library, pycsco which is not catching wrong values returned by the NX-API.

Feel free to submit a PR and replace the line 207:

``` python
formatted_info['is_enabled'] = 'up' in intf_info.get('admin_state').lower()
```

with 

``` python
formatted_info['is_enabled'] = 'up' in (intf_info.get('admin_state', '') or '').lower()
```

**Comment by mirceaulinic** [comment]
This is not a solution, just a hot fix just to make it work. It will definitely fail in other cases (other lines will throw AttributeError exceptions). To cover all, I will need https://github.com/napalm-automation/napalm-base/pull/21 firstly merged and use the `convert` helper.

**Comment by dbarrosop** [comment]
Is this still in progress?

**Comment by jzohrab** [comment]
@mirceaulinic - https://github.com/napalm-automation/napalm-base/pull/21 has been merged.

**Comment by mirceaulinic** [comment]
Thanks for reminder @jzohrab, it is on my todo list already.

**Comment by mirceaulinic** [comment]
Closed via https://github.com/napalm-automation/napalm-nxos/pull/41
