### ISSUE TITLE
"No JSON object could be decoded" when running .get_facts()

### ISSUE THREAD

**Issue by mattschwen** [napalm-automation/napalm-nxos#96]
### Description of Issue/Question
First time using NAPALM and trying to connect using NX-API to run simple .get_facts() test. When connecting and running this module I get the following error:

```
ValueError: No JSON object could be decoded
```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[x] Yes
[ ] No

### napalm-nxos version
(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

```
napalm-nxos==0.5.2
```

### NX-OS version
(Paste verbatim output from `show version | json` between quotes below)

```json
{
  "header_str": "Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nCopyright (C) 2002-2016, Cisco and/or its affiliates.\nAll rights reserved.\nThe copyrights to certain works contained in this software are\nowned by other third parties and used and distributed under their own\nlicenses, such as open source.  This software is provided \"as is,\" and unless\notherwise stated, there is no warranty, express or implied, including but not\nlimited to warranties of merchantability and fitness for a particular purpose.\nCertain components of this software are licensed under\nthe GNU General Public License (GPL) version 2.0 or \nGNU General Public License (GPL) version 3.0  or the GNU\nLesser General Public License (LGPL) Version 2.1 or \nLesser General Public License (LGPL) Version 2.0. \nA copy of each such license is available at\nhttp://www.opensource.org/licenses/gpl-2.0.php and\nhttp://opensource.org/licenses/gpl-3.0.html and\nhttp://www.opensource.org/licenses/lgpl-2.1.php and\nhttp://www.gnu.org/licenses/old-licenses/library.txt.",
  "bios_ver_str": "07.51",
  "kickstart_ver_str": "7.0(3)I4(2)",
  "bios_cmpl_time": "02/15/2016",
  "kick_file_name": "bootflash:///nxos.7.0.3.I4.2.bin",
  "kick_cmpl_time": "7/21/2016 8:00:00",
  "kick_tmstmp": "07/21/2016 16:09:32",
  "chassis_id": "Nexus9000 C9372PX chassis",
  "cpu_name": "Intel(R) Core(TM) i3- CPU @ 2.50GHz",
  "memory": "16401548",
  "mem_type": "kB",
  "proc_board_id": "SAL1945SFEQ",
  "host_name": "sja06edrtor-g-7",
  "bootflash_size": "51496280",
  "kern_uptm_days": "194",
  "kern_uptm_hrs": "2",
  "kern_uptm_mins": "57",
  "kern_uptm_secs": "40",
  "rr_reason": "Unknown",
  "rr_sys_ver": "7.0(3)I4(2)",
  "rr_service": null,
  "manufacturer": "Cisco Systems, Inc."
}
```

### Error Traceback

```python
Traceback (most recent call last):
  File "testhost.py", line 19, in <module>
    e.get_facts()
  File "/usr/local/lib/python2.7/dist-packages/napalm_nxos/nxos.py", line 353, in get_facts
    pynxos_facts = self.device.facts
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 224, in facts
    show_version_facts = self._get_show_version_facts()
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 197, in _get_show_version_facts
    show_version_result = self.show(u'show version')
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 49, in show
    list_result = self.show_list(commands, raw_text)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 63, in show_list
    response_list = self._cli_command(commands)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/device.py", line 38, in _cli_command
    rpc_response = self.rpc.send_request(commands, method=method, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/pynxos/lib/rpc_client.py", line 51, in send_request
    response_list = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
### How I Am Generating Connection

```python
import getpass
import json
import napalm
import os
import sys


def main():

	DRIVER = 'nxos'
	HOSTNAME = [NEXUSDEVICE]
	USERNAME = [USERNAME]
	PASSWORD = getpass.getpass()

	d = napalm.get_network_driver(DRIVER)
	e = d(HOSTNAME, USERNAME, PASSWORD, optional_args={'config_lock': False})

	e.open()
	e.get_facts()
	e.close()


if __name__ == '__main__':
	main()
```

**Comment by mattschwen** [comment]
I have created a script to test NX-API requests and parse the JSON manually using the JSON library. When communicating via HTTPS with the device, I had to add the following to the request due to the switch having an unverified cert. Not sure if this is related, but something to look at. 

May be a nice optional arg?

```
verify=False

Example:

response = requests.post(url,data=json.dumps(payload), verify=False, headers=myheaders,auth=(username,password)).json()

```

**Comment by mirceaulinic** [comment]
Hi @mattschwen I agree on an optional arg regarding the certificate verification (we may need it for other HTTP-based drivers). We can call it `ssl_verify`.

I would be tempted to say that the root cause comes from the fact that the device does not have a JSON equivalent. But from the logs, it looks like that it fails when executing `show version` which you have provided the JSON so yes, so it may be related to HTTPS/HTTP, although I don't see how. You can use the `nxos_protocol` arg, setting it to `http`, making sure you're using the right port.

As you're a Salt user, I would suggest starting the proxy in debug more (`salt-proxy --proxyid <device> -l debug`) and collect the logs when trying to collect - is it able to execute the `open` successfully (I am thinking that maybe it's not able to connect actually, but `open` does not throw any error)?

**Comment by mattschwen** [comment]
Hey @mirceaulinic, I am still in the process of setting up and learning Salt. Wanted to know everything about NAPALM  before I did that :). 

I believe what you mentioned about the expected JSON not matching what the switch is returning is likely the error. Is there a link or reference you can provide me that shows what the different .get modules are expecting as far as JSON goes?

**Comment by mirceaulinic** [comment]
Hi @mattschwen:

> I am still in the process of setting up and learning Salt. Wanted to know everything about NAPALM before I did that :).

I was asking about Salt as it's easier to collect logs.

> I believe what you mentioned about the expected JSON not matching what the switch is returning is likely the error. Is there a link or reference you can provide me that shows what the different .get modules are expecting as far as JSON goes?

I'm not aware of any Cisco documentation presenting the structure (wondering if they have any internal document - the structure seems to change often anyway).

Can you try the folllwing Python script and let me know the result, I think I may have identified your issue, waiting for your confirmation :-)


```python
import requests
from requests.auth import HTTPBasicAuth
import json

from builtins import range
from pynxos.errors import NXOSError

# requests.packages.urllib3.disable_warnings()

class RPCClient(object):
    def __init__(self, host, username, password, transport=u'http', port=None):
        if transport not in ['http', 'https']:
            raise NXOSError('\'%s\' is an invalid transport.' % transport)
        if port is None:
            if transport == 'http':
                port = 80
            elif transport == 'https':
                port = 443
        self.url = u'%s://%s:%s/ins' % (transport, host, port)
        self.headers = {u'content-type': u'application/json-rpc'}
        self.username = username
        self.password = password
    def _build_payload(self, commands, method, rpc_version=u'2.0'):
        payload_list = []
        id_num = 1
        for command in commands:
            payload = dict(jsonrpc=rpc_version,
                           method=method,
                           params=dict(cmd=command, version=1),
                           id=id_num,)
            payload_list.append(payload)
            id_num += 1
        return payload_list
    def send_request(self, commands, method=u'cli', timeout=30):
        timeout=int(timeout)
        payload_list = self._build_payload(commands, method)
        print(payload_list)
        response = requests.post(self.url,
                                 timeout=timeout,
                                 data=json.dumps(payload_list),
                                 headers=self.headers,
                                 auth=HTTPBasicAuth(self.username, self.password),
                                 verify=False)
        print(response)
        print(response.text)
        response_list = json.loads(response.text)
        if isinstance(response_list, dict):
            response_list = [response_list]
        for i in range(len(commands)):
            response_list[i][u'command'] = commands[i]
        return response_list

rpc = RPCClient('HOST', 'USER', 'PASS')
rpc.send_request(['show version'])
```

(it is basically the https://github.com/networktocode/pynxos/blob/master/pynxos/lib/rpc_client.py module with some print statements)

**Comment by mattschwen** [comment]
@mirceaulinic 

Here is the exact output from running script that against the same device I was initially testing with:

```
[{'params': {'cmd': 'show version', 'version': 1}, 'jsonrpc': u'2.0', 'id': 1, 'method': u'cli'}]
<Response [200]>
{
	"jsonrpc":	"2.0",
	"result":	{
		"body":	{
			"header_str":	"Cisco Nexus Operating System (NX-OS) Software\nTAC support: http://www.cisco.com/tac\nCopyright (C) 2002-2016, Cisco and/or its affiliates.\nAll rights reserved.\nThe copyrights to certain works contained in this software are\nowned by other third parties and used and distributed under their own\nlicenses, such as open source.  This software is provided \"as is,\" and unless\notherwise stated, there is no warranty, express or implied, including but not\nlimited to warranties of merchantability and fitness for a particular purpose.\nCertain components of this software are licensed under\nthe GNU General Public License (GPL) version 2.0 or \nGNU General Public License (GPL) version 3.0  or the GNU\nLesser General Public License (LGPL) Version 2.1 or \nLesser General Public License (LGPL) Version 2.0. \nA copy of each such license is available at\nhttp://www.opensource.org/licenses/gpl-2.0.php and\nhttp://opensource.org/licenses/gpl-3.0.html and\nhttp://www.opensource.org/licenses/lgpl-2.1.php and\nhttp://www.gnu.org/licenses/old-licenses/library.txt.\n",
			"bios_ver_str":	"07.51",
			"kickstart_ver_str":	"7.0(3)I4(2)",
			"bios_cmpl_time":	"02/15/2016",
			"kick_file_name":	"bootflash:///nxos.7.0.3.I4.2.bin",
			"kick_cmpl_time":	" 7/21/2016 8:00:00",
			"kick_tmstmp":	"07/21/2016 16:09:32",
			"chassis_id":	"Nexus9000 C9372PX chassis",
			"cpu_name":	"Intel(R) Core(TM) i3- CPU @ 2.50GHz",
			"memory":	16401548,
			"mem_type":	"kB",
			"proc_board_id":	"SAL1945SFEQ",
			"host_name":	"sja06edrtor-g-7",
			"bootflash_size":	51496280,
			"kern_uptm_days":	200,
			"kern_uptm_hrs":	5,
			"kern_uptm_mins":	27,
			"kern_uptm_secs":	27,
			"rr_reason":	"Unknown",
			"rr_sys_ver":	"7.0(3)I4(2)",
			"rr_service":	"",
			"manufacturer":	"Cisco Systems, Inc."
		}
	},
	"id":	1
}
```

**Comment by mirceaulinic** [comment]
@mattschwen Good - now, please do the same with the following:

- `show interface`
- `show interface status`
- `show hostname`
- `show vlan`

(these are collected when executing `get_facts`).

I suppose that one or more requests fail, or don't provide the fields as expected (to investigate later, after you confirm)

**Comment by mattschwen** [comment]
@mirceaulinic All commands work and return information:

[Archive.zip](https://github.com/napalm-automation/napalm-nxos/files/1112720/Archive.zip)

I did not include the full 'show interface' due to un-necessary information, but you can see the structure.

**Comment by mirceaulinic** [comment]
Thanks for checking @mattschwen.

In the networktocode #saltstack channel, you have stated this:

> Is the only option to use NX-API? Can you use SSH? I only ask because Cisco currently has a bug which dis-allows JSON-RPC queries when authenticating via TACACS and have Authorization-Commands enabled. 

Can you make sure you can execute the script above __with the same username__? From that statement, my understanding is that you won't be able to use `napalm-nxos` with usernames authenticated through tacacs.

**Comment by mattschwen** [comment]
@mirceaulinic 

I am digging deep with Cisco on this problem and am having them fix the bug ASAP. I do believe, however, that this particular issue is not related to the TACACS bug I am hitting on other devices. Mainly because JSON-RPC queries return information just fine with this device. If you hit the TACACS bug and try to query JSON-RPC you will relieve the following message: 

`Error: AAA authorization failed AAA_AUTHOR_STATUS_METHOD=16(0x10) `

You can see others hitting the TACACS bug here: https://communities.cisco.com/thread/51144?start=0&tstart=0

**Comment by mattschwen** [comment]
@mirceaulinic 

I will re-tract my last statement and say that you are correct. I fixed the TACACS issue by removing a specific policy in Cisco ISE (used for radius auth) and re-ran the NAPALM tests and everything works fine. 

.get_facts() returns everything correctly. 

We use Generic AD accounts for automation scripts. In Cisco ISE we have a policy that allows you to only use Generic AD account from specific IP's to keep us more secure. There is a bug associated with that policy (Cisco is aware is is going to fix it in an update). 

We can consider this resolved.

**Comment by mirceaulinic** [comment]
Great, thanks for info @mattschwen.
