### ISSUE TITLE
Feature request:  Optional argument port

### ISSUE THREAD

**Issue by pmusolino-rms** [napalm-automation/napalm-nxos#99]
### Description of Issue/Question
It would be helpful to be able to specify the nxos port in addition to the transport in the cases where default of 80/443 is not used

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[X ] Yes
[ ] No

### napalm-nxos version
(Paste verbatim output from `pip freeze | grep napalm-nxos` between quotes below)

```
napalm-nxos==0.5.3
```

### NX-OS version
(Paste verbatim output from `show version | json` between quotes below)

```
pipe to json broken on nexus 5548.  version 7.3(2)N1(1)
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Its a feature request.  No errors.
```

**Comment by ktbyers** [comment]
@pmusolino-rms It already does this:

https://github.com/napalm-automation/napalm-nxos/blob/develop/napalm_nxos/nxos.py#L67-L70

If it doesn't work, just re-open the issue.
